---
- name: main / add the OS specific varibles
  include_vars: "{{ ansible_os_family}}.yml"

# yum
- name: main / update yum packages
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - "epel-release"
    - "*"
  when: ansible_os_famiry == 'CentOS'

# apt
- name: main / update apt packages
  apt:
    update_cache: yes
  when: ansible_os_famiry == 'Debian'

- name: main / install the required packages
  package:
    name: "{{ item }}"
    state: present
    with_items: "{{ required_packages }}"