- name: bind install
  hosts: localhost
  tasks:
    - name: bind-chroot install
      yum: name=bind-chroot
    - name: start & enable named
      systemd:
        name: named
        state: started
        daemon_reload: yes
        enabled: yes